Fixing a parsing error.
nbes4/spektrum-packet-analyzer pull request #1
Opened 2024-06-23 17:26 UTC by serg-bloim

The error happens when packet contains field 'id' that is not in CHANNEL_NAMES

2024-06-23 20:04 UTC, nbes4 requested changes
Hi @serg-bloim! Thank you so much for your PR! I reviewed it and it looks good, only a very-small nitpick regarding the returned string. 😄

2024-06-23 20:04 UTC, nbes4 commented on SpektrumPacketAnalyzer.py
> +            return "NOT_IDENTIFIED"
Could you change this string from `"NOT_IDENTIFIED"` to `"Unknown"`? I think that would fit better with the rest 👍

2024-06-27 18:50 UTC, serg-bloim commented on SpektrumPacketAnalyzer.py
> +            return "NOT_IDENTIFIED"
Sure thing, let me change it.

2024-06-28 19:12 UTC, nbes4 approved these changes

2024-06-28 19:13 UTC, merged

2024-06-28 19:14 UTC, nbes4 commented
Awesome, I squashed the commits and merged them. Thanks again, @serg-bloim. 🎉